apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-48bm
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gpbg-tenant/rhtap-demo-app/hacbs-test-project-48bm@sha256:8cacea7cf73598575f29f871ab0de66789dc768263f6942d227cc592b7f1f5ad
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
