apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-48bm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-48bm
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-48bm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-48bm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-48bm
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-gpbg-tenant/rhtap-demo-app/hacbs-test-project-48bm@sha256:8cacea7cf73598575f29f871ab0de66789dc768263f6942d227cc592b7f1f5ad
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
